from __future__ import annotations

from typing import Protocol


class UserRepository(Protocol):
    def get(self, login_key: str) -> dict | None: ...

    def get_by_profile_id(self, profile_id: str) -> dict | None: ...

    def save(self, login_key: str, user: dict) -> None: ...

    def all(self) -> dict[str, dict]: ...


class ProfileRepository(Protocol):
    def get(self, profile_id: str) -> dict | None: ...

    def save(self, profile: dict) -> None: ...

    def all(self) -> dict[str, dict]: ...


class SessionRepository(Protocol):
    def get(self, token: str) -> dict | None: ...

    def save(self, token: str, session: dict) -> None: ...

    def revoke(self, token: str) -> bool: ...

    def purge_expired(self, now: float) -> int: ...

    def all(self) -> dict[str, dict]: ...
